//
//  IntroView.swift
//  handbot
//
//  Created by carton22 on 2023/4/14.
//

import SwiftUI

struct IntroView: View {
    @Binding var showintro: Bool
    
    var body: some View {
        NavigationView{
            ZStack{
                Color.darkBackground.ignoresSafeArea()
                    GeometryReader{
                        geometry in
                        VStack{
                            VStack(alignment: .leading) {
                                
                                Text("This is handbot playground! Here, you can immerse into the world of AIGC! Now, every edit counts! In the content generated by AI, please boldly try to modify and edit, and give full play to your initiative! Following are some tips!💡")
                                    .font(.headline)
                                    .padding(.bottom, 5)
                                
                                Rectangle()
                                    .frame(height: 2)
                                    .foregroundColor(.lightBackground)
                                    .padding(.vertical)
                                //                            Text
                                Text("Text✒️")
                                    .font(.title.bold())
                                    .padding(.bottom, 5)
                                
                                Text("1. Click the generated word\n2. Edit the word\n3. Drag the word and view the animation")
                                    .font(.headline)
                                    .padding(.bottom, 5)
                                
                                Rectangle()
                                    .frame(height: 2)
                                    .foregroundColor(.lightBackground)
                                    .padding(.vertical)
                                //                            Paint
                                Text("Paint🎨")
                                    .font(.title.bold())
                                    .padding(.bottom, 5)
                                
                                Text("1. Click the generated picture\n2. Paint it as you like")
                                    .font(.headline)
                                    .padding(.bottom, 5)
                                //                            Audio
                                Rectangle()
                                    .frame(height: 2)
                                    .foregroundColor(.lightBackground)
                                    .padding(.vertical)
                                
                                Text("Audio🎵")
                                    .font(.title.bold())
                                    .padding(.bottom, 5)
                                
                                Text("1. Play the AI-generated audio\n2. Make some comments\n3. Submit it!\n\n\n\nEvery time you edit, you will get a certain score. I hope you can re-examine the relationship between humans and machines in the AIGC era, and maximize the subjective initiative of humans.Eventually, human hand and machine hand will be closely intertwined👨🤝🤖️")
                                    .font(.headline)
                                    .padding(.bottom, 5)
                                
                                
                            }
                            .padding(.horizontal)
                            Button(action: {
                                showintro = false
                            }) {
                                Text("Begin now!")
                                    .font(.headline)
                                    .foregroundColor(.white)
                                    .padding()
                                    .background(Color.blue)
                                    .cornerRadius(20)
                            }
                        }
                        
                    }.navigationTitle("Welcome to Handbot!👐")
                        .preferredColorScheme(.dark)
                }
            }
    }
}

